default_platform(:android)

platform :android do
  desc "Build APK and upload to Firebase"
  lane :beta do
    gradle(
      task: "assemble",
      build_type: "Release"
    )

    firebase_app_distribution(
      app: "1:471625841737:android:604613a3e5062dd8a65398",
      testers: "chiragdhunna2468@@gmail.com", # comma-separated
      release_notes: "Auto build from GitHub Actions"
    )
  end
end
